title: Graham Mueller
description: Attending Oregon State University, <a href="https://eecs.oregonstate.edu/undergraduate/ece"> ECE </a>
resume_description: <a href="https://github.com/Muellegr/Muellegr.github.io/blob/master/Resume/resume.pdf"> Resume </a>
resume_link: https://github.com/Muellegr/Muellegr.github.io/blob/master/Resume/resume.pdf
google_analytics:
theme: jekyll-theme-slate


