title: Graham Mueller
description: Attending Oregon State University, <a href="https://eecs.oregonstate.edu/undergraduate/ece"> ECE </a>
resume_description: <a href="https://raw.githubusercontent.com/Muellegr/Muellegr.github.io/master/Resume/resume.pdf"> Resume </a>
resume_link: https://raw.githubusercontent.com/Muellegr/Muellegr.github.io/master/Resume/resume.pdf
google_analytics:
theme: jekyll-theme-slate


