title: Graham Mueller
description: Attending Oregon State University, <a href="https://eecs.oregonstate.edu/undergraduate/ece"> ECE </a>
resume_description: <a href="https://google.com"> Resume </a>
resume_link: http://google.com
google_analytics:
theme: jekyll-theme-slate


